import type { NextPage, GetServerSidePropsContext } from 'next'
import fs from 'fs'
import path from 'path'
import yaml from 'js-yaml'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

import type { Config } from '../lib/types'

import SearchBox from '../components/SearchBox'
import Links from '../components/Links'

interface HomeProps {
  config: Config
}

const Home: NextPage<HomeProps> = ({ config }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{ config.general.title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Good evening, Simon
        </h1>

        <SearchBox />

        <Links links={config.links} />
      </main>
    </div>
  )
}

export default Home

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const configFile = fs.readFileSync(path.join(process.cwd(), process.env.CONFIG_FILE), 'utf8')

  const config = yaml.load(configFile) as Config



  return {
    props: {
      config
    }, // will be passed to the page component as props
  }
}