name: Build and release Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2

      - 
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Gather metadata for Docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/simse/homepage

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}